# docker-compose.yml
version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: ratings-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratingsdb
      MYSQL_USER: ratings_user
      MYSQL_PASSWORD: ratings_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ratings-data-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mongodb:
    image: mongo:6.0
    container_name: movie-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: