spring.application.name=top-movies-service

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ratingsdb
spring.datasource.username=ratings_user
spring.datasource.password=ratings_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

grpc.server.port=9091